spring:
  profiles:
    active:
      - dev

---
server:
  port: 9001
spring:
  application:
    name: AIGOU_ZUUL
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
zuul:
  ignored-services: /*
  prefix: /aigou
  routes:
    aigou_plat: /login/**
    aigou_product: /pruduct/**
